### ISSUE TITLE
Consider using a button-link for (De)Select All

### ISSUE THREAD

**Issue by ocean90** [wearerequired/WP-Widget-Disable#13]
**Before:**
<img width="750" alt="bildschirmfoto 2016-12-07 um 22 30 39" src="https://cloud.githubusercontent.com/assets/617637/20987420/d560eac2-bccc-11e6-9b38-fed0b65c8034.png">

**After:**
<img width="627" alt="bildschirmfoto 2016-12-07 um 22 29 40" src="https://cloud.githubusercontent.com/assets/617637/20987391/ba6374a6-bccc-11e6-83c2-0b1515ca7a2d.png">

**Comment by swissspidy** [comment]
+1 to improved accessibility
