### ISSUE TITLE
Remove "WP" Prefix from plugin name

### ISSUE THREAD

**Issue by ocean90** [wearerequired/WP-Widget-Disable#38]
<img width="643" alt="bildschirmfoto 2018-10-05 um 10 32 33" src="https://user-images.githubusercontent.com/617637/46524713-fddd1780-c889-11e8-9a1c-0c838b7ef559.png">

It's a WordPress plugin so the "WP" prefix isn't really necessary IMO.

**Comment by swissspidy** [comment]
😱 

So you suggest removing the prefix everywhere or just from the readme / plugin directory page?

**Comment by ocean90** [comment]
* https://github.com/wearerequired/WP-Widget-Disable/blob/1.9.0/wp-widget-disable.php#L3
* https://github.com/wearerequired/WP-Widget-Disable/blob/1.9.0/readme.txt#L1
* https://github.com/wearerequired/WP-Widget-Disable/blob/1.9.0/wp-widget-disable.php#L37
