### ISSUE TITLE
Update plugin banner

### ISSUE THREAD

**Issue by ocean90** [wearerequired/WP-Widget-Disable#39]
https://plugins.svn.wordpress.org/wp-widget-disable/assets/banner-1544x500.png doesn't show the current version of the plugin.

**Comment by grappler** [comment]
For consistency sake we will use similar style banners for the plugins and just update the screenshots.
![image](https://user-images.githubusercontent.com/1785641/47364021-848e5300-d6d8-11e8-857f-617c764feb87.png)
![image](https://user-images.githubusercontent.com/1785641/47364026-8b1cca80-d6d8-11e8-8873-398f39d26e7e.png)
