### ISSUE TITLE
Disable editor blocks

### ISSUE THREAD

**Issue by swissspidy** [wearerequired/WP-Widget-Disable#41]
Should we consider adding an option to disable editor blocks across the board?

There are plugins like https://wordpress.org/plugins/manager-for-gutenberg/ that offer this as well, but perhaps our users would like to have this integrated into this plugin.

**Comment by grappler** [comment]
I don't think so. We can relook at this once Widgets are integrated into the block editor.

The plugin name would not make this feature easily searchable and I don''t think we should bloat the plugin and create additional work/support.
