### ISSUE TITLE
Buchstabendreher (Typo) in description

### ISSUE THREAD

**Issue by zu** [wearerequired/WP-Widget-Disable#6]
rplus_wp_widget_disable_default_dashboard_filter gives you back the list (array) of all dashboard widgets before we *sotre* them, so you could basically remove dashboard widgets from being disabled.

store

**Comment by swissspidy** [comment]
Dankeschön. Werde wohl am besten ma den ganzen Satz umschreiben.

**Comment by swissspidy** [comment]
Fixed in the `develop` branch.
