### ISSUE TITLE
Duplicate notices

### ISSUE THREAD

**Issue by swissspidy** [wearerequired/WP-Widget-Disable#7]
The success message is always displayed twice.

**Comment by swissspidy** [comment]
Can't reproduce.

**Comment by swissspidy** [comment]
Apparently still an issue

<img width="438" alt="screen shot 2016-07-10 at 16 41 40" src="https://cloud.githubusercontent.com/assets/841956/16714254/4cff5e3c-46bd-11e6-8342-ae4a7c0acaf0.png">

**Comment by swissspidy** [comment]
Funnily this only happens when 1 widget is disabled, not when checking multiple boxes.

**Comment by neverything** [comment]
Maybe it's because of the `settings_errors()` call? https://github.com/wearerequired/WP-Widget-Disable/blob/ae63e7881d71a0eaf7b337bf15ca26a2a0d8c770/views/admin.php#L18

See "duplicate admin notices": https://digwp.com/2016/05/wordpress-admin-notices/

**Comment by swissspidy** [comment]
D'oh, that indeed sounds like a duplicated call to display settings errors.

**Comment by swissspidy** [comment]
Now I can't reproduce it again. So fun.
